export const profiles = {
  github: {
    id: '888888',
    displayName: 'Github Person',
    username: 'ghperson',
    profileUrl: 'https://github.com/ghperson',
    photos: [{ value: 'https://avatars1.githubusercontent.com/u/888888?v=4' }],
    provider: 'github',
    _raw:
      '{"login":"ghperson","id":888888,"node_id":"MDQ6VXNlcjg2MzAyMA==","avatar_url":"https://avatars1.githubusercontent.com/u/888888?v=4","gravatar_id":"","url":"https://api.github.com/users/ghperson","html_url":"https://github.com/ghperson","followers_url":"https://api.github.com/users/ghperson/followers","following_url":"https://api.github.com/users/ghperson/following{/other_user}","gists_url":"https://api.github.com/users/ghperson/gists{/gist_id}","starred_url":"https://api.github.com/users/ghperson/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ghperson/subscriptions","organizations_url":"https://api.github.com/users/ghperson/orgs","repos_url":"https://api.github.com/users/ghperson/repos","events_url":"https://api.github.com/users/ghperson/events{/privacy}","received_events_url":"https://api.github.com/users/ghperson/received_events","type":"User","site_admin":false,"name":"Github Person","company":null,"blog":"ghperson.com","location":null,"email":null,"hireable":null,"bio":null,"twitter_username":null,"public_repos":29,"public_gists":28,"followers":3,"following":5,"created_at":"2011-06-21T00:17:38Z","updated_at":"2020-08-11T19:58:53Z"}',
    _json: {
      login: 'ghperson',
      id: 888888,
      node_id: 'MDQ6VXNlcjg2MzAyMA==',
      avatar_url: 'https://avatars1.githubusercontent.com/u/888888?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/ghperson',
      html_url: 'https://github.com/ghperson',
      followers_url: 'https://api.github.com/users/ghperson/followers',
      following_url: 'https://api.github.com/users/ghperson/following{/other_user}',
      gists_url: 'https://api.github.com/users/ghperson/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/ghperson/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/ghperson/subscriptions',
      organizations_url: 'https://api.github.com/users/ghperson/orgs',
      repos_url: 'https://api.github.com/users/ghperson/repos',
      events_url: 'https://api.github.com/users/ghperson/events{/privacy}',
      received_events_url: 'https://api.github.com/users/ghperson/received_events',
      type: 'User',
      site_admin: false,
      name: 'Github Person',
      company: null,
      blog: 'ghperson.com',
      location: null,
      email: null,
      hireable: null,
      bio: null,
      twitter_username: null,
      public_repos: 29,
      public_gists: 28,
      followers: 3,
      following: 5,
      created_at: '2011-06-21T00:17:38Z',
      updated_at: '2020-08-11T19:58:53Z',
    },
    emails: [
      { value: 'ghperson@example.com', primary: true, verified: true },
      { value: 'ghperson1@example.com', primary: false, verified: true },
      { value: 'ghperson2@example.com', primary: false, verified: false }
    ],
  }
}
